name: Python CI
on: [ push, pull_request ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10.4 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          chmod +x ./setup_environment.sh
          ./setup_environment.sh cpu

      - name: Run tests with virtual environment
        run: |
          source $HOME/venv/slurm-pytorch-ddp-boilerplate/bin/activate
          pytest
